FROM ubuntu:18.10

COPY ./dana ./home/renato/dana
RUN chmod 755 ./home/renato/dana
COPY . ./home/renato/smrr
ENV DANA_HOME=/home/renato/dana/
ENV PATH="${PATH}:/home/renato/dana/"
WORKDIR /home/renato/smrr

CMD ["dana", "ServerlessHDR.o"]